minimum_pre_commit_version: 1.15.2
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
        language_version: python3
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        language_version: python3
      - id: mixed-line-ending
        args: [--fix=lf]
        language_version: python3
      - id: end-of-file-fixer
        language_version: python3
      - id: check-ast
        language_version: python3
      - id: check-toml
      - id: check-json
      - id: check-symlinks

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
      - id: insert-license
        language: python
        files: ^(cpe_tag)\/(?!.*__init__\.py).+\.py$
        args: [--license-filepath, "header.txt"]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [--count, "--ignore=E501", --show-source, --statistics]

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--profile, black]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        args: []
